### ISSUE TITLE
Doc Misspelling

### ISSUE THREAD

**Issue by IcicleF** [kainwen/liblambdaOJ2#2]
doc/lamdbaOJ2.md: Line 71, -std=c++03 -> -std=c++11

**Comment by kainwen** [comment]
@IcicleF 
Thanks a lot. I will fix this.

However, the current doc is not exactly the same as the implementations.

**Comment by kainwen** [comment]
Fixed in this commit https://github.com/kainwen/liblambdaOJ2/commit/6028850d428141453d598646e82552c5bbccc151 .
